//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int AccountID { get; set; }
        public string CardNO { get; set; }
        public string Pin { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
