//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine
{
    using System;
        
    public partial class CashMoney
    {

        public CashMoney() { }
        public CashMoney(double? moneyValue, int quantity)
        {
            MoneyValue = moneyValue;
            Quantity = quantity;
        }

        public int MoneyID { get; set; }
        public Nullable<double> MoneyValue { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
