//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine
{
    using System;
     
    public partial class Product
    {

        public Product(){}

        public Product(string name, int quantity, double price)
        {
            ProductName = name;
            Quantity = quantity;
            Price = price;
        }

        public Product(int productId, string name, int quantity, double price)
        {
            ProductsID = productId;
            ProductName = name;
            Quantity = quantity;
            Price = price;
        }

        public int ProductsID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }

       
        public override String ToString() {

            return $"Id: {ProductsID} Name: {ProductName} Quantity: {Quantity} Price: {Price}";

        }
    }
}
